# Generated by Django 5.0.2 on 2024-11-19 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfadfinderfahrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('ziel', models.CharField(blank=True, max_length=255, null=True)),
                ('start_zeit', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_zeit', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_ort', models.CharField(max_length=255)),
                ('end_ort', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='fahrten/')),
            ],
        ),
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmelde_zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrten.pfadfinderfahrt')),
            ],
            options={
                'unique_together': {('user', 'fahrt')},
            },
        ),
    ]
