# Generated by Django 5.0.2 on 2024-06-12 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfadfinderfahrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('ziel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('motto', models.CharField(max_length=255)),
                ('start_zeit', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_zeit', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_ort', models.CharField(max_length=255)),
                ('end_ort', models.CharField(max_length=255)),
            ],
        ),
    ]
