# Generated by Django 5.0.2 on 2024-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfadfinderfahrt',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pfadfinderfahrt',
            name='ziel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
