# Generated by Django 5.0.2 on 2024-06-12 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrten', '0002_alter_pfadfinderfahrt_motto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmelde_zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('fahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrten.pfadfinderfahrt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fahrt')},
            },
        ),
    ]
