# Generated by Django 5.0.2 on 2024-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrten', '0003_anmeldung'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfadfinderfahrt',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='fahrten/'),
        ),
    ]
